### ISSUE TITLE
Update to the latest Love version?

### ISSUE THREAD

**Issue by flamendless** [kikito/love-loader#18]
Hey, want to update this to work with 0.10?

**Comment by kikito** [comment]
Hi there. I just assumed that it did work on the latest version of LÖVE, but I have not tried it, to be honest (It turns out that I can only afford to do really small games, so I actually don't need something like love-loader most of the time).

Does love-loader break on the latest LÖVE? What error did you get?

**Comment by kikito** [comment]
Hi, I have marked this project as deprecated and will close all open issues.
